# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat_service.proto\x12\x04\x63hat\"2\n\x0b\x43hatRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"8\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x19\n\x11suggested_actions\x18\x02 \x03(\t\"\x14\n\x12HealthCheckRequest\";\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t2\x87\x01\n\x0b\x43hatService\x12\x34\n\x0bSendMessage\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse\x12\x42\n\x0bHealthCheck\x12\x18.chat.HealthCheckRequest\x1a\x19.chat.HealthCheckResponseB\x1f\n\x1b\x63om.potato.mainservice.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.potato.mainservice.grpcP\001'
  _globals['_CHATREQUEST']._serialized_start=28
  _globals['_CHATREQUEST']._serialized_end=78
  _globals['_CHATRESPONSE']._serialized_start=80
  _globals['_CHATRESPONSE']._serialized_end=136
  _globals['_HEALTHCHECKREQUEST']._serialized_start=138
  _globals['_HEALTHCHECKREQUEST']._serialized_end=158
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=160
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=219
  _globals['_CHATSERVICE']._serialized_start=222
  _globals['_CHATSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
